swaylock \
	--screenshots \
	--clock \
	--indicator \
	--indicator-radius 100 \
	--indicator-thickness 22 \
	--effect-blur 9x7 \
	--effect-vignette 0.5:0.5 \
	--text-color 1e1e1c \
	--ring-color 88b7e3 \
	--key-hl-color 8b3e67 \
	--line-color cedae5 \
	--inside-color e5e3d8 \
	--separator-color b7c1cb \
	--grace 0 \
	--fade-in 0.2 \
	--daemonize