swaylock \
	--screenshots \
	--clock \
	--indicator \
	--indicator-radius 100 \
	--indicator-thickness 10 \
	--effect-blur 9x7 \
	--effect-vignette 0.5:0.5 \
	--text-color 151e16 \
	--ring-color 87995b \
	--key-hl-color 658b3e \
	--line-color dee5ce \
	--inside-color cee5d0 \
	--separator-color c5cbb7 \
	--grace 0 \
	--fade-in 0.2 \
	--daemonize