swaylock \
	--screenshots \
	--clock \
	--indicator \
	--indicator-radius 100 \
	--indicator-thickness 4 \
	--effect-blur 9x7 \
	--effect-vignette 0.5:0.5 \
	--text-color beb7cc \
	--ring-color beb7cc \
	--key-hl-color 9a8eb2 \
	--line-color beb7cc \
	--inside-color 232226 \
	--separator-color a6a0b2 \
	--grace 0 \
	--fade-in 0.2 \
	--daemonize